# server配置
server:
  port: 8088
  servlet:
    context-path: /

# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///where
      username: root
      password: '123456'
      driver-class-name: com.mysql.cj.jdbc.Driver


# mybatis-plus的配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto #主键策略自增长

#jwt配置
jwt:
  token:
    tokenExpiration: 120 #有效时间,单位分钟
    tokenSignKey: where123456  #当前程序签名秘钥 自定义



